
name: passcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '* */6 * * *' # 每6小时监测一次

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install bs4

      - name: Working
        env:
          URL: ${{ secrets.URL }}
          BARKTOKEN: ${{ secrets.BARKTOKEN }}
        run: python pass_check.py
          
